export const createAction = (type) => (payload) => ({
  type,
  payload,
});
export const LOGIN_LOAD = "LOGIN_LOAD";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const REGIST_LOAD = "REGIST_LOAD";
export const REGIST_SUCCESS = "REGIST_SUCCESS";
export const REGIST_FAILED = "REGIST_FAILED";

export const SIGNOUT_LOAD = "SIGNOUT_LOAD";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_FAILED = "SIGNOUT_FAILED";

export const CLEAR_TOKEN = "CLEAR_TOKEN";

export const FORGOT_PASS_LOAD = "FORGOT_PASS_LOAD";
export const FORGOT_PASS_SUCCESS = "FORGOT_PASS_SUCCESS";
export const FORGOT_PASS_FAILED = "FORGOT_PASS_FAILED";

export const RESET_PASS_LOAD = "RESET_PASS_LOAD";
export const RESET_PASS_SUCCESS = "RESET_PASS_SUCCESS";
export const RESET_PASS_FAILED = "RESET_PASS_FAILED";

export const CHANGE_PASS_LOAD = "CHANGE_PASS_LOAD";
export const CHANGE_PASS_SUCCESS = "CHANGE_PASS_SUCCESS";
export const CHANGE_PASS_FAILED = "CHANGE_PASS_FAILED";

export const GET_ACCOUNT_LOAD = "GET_ACCOUNT_LOAD";
export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS";
export const GET_ACCOUNT_FAILED = "GET_ACCOUNT_FAILED";
/** EMPLOYEE TYPE */
export const GET_EMPLOYEE_LOAD = "GET_EMPLOYEE_LOAD";
export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYEE_SUCCESS";
export const GET_EMPLOYEE_FAILED = "GET_EMPLOYEE_FAILED";

export const GET_EMPLOYEEID_LOAD = "GET_EMPLOYEEID_LOAD";
export const GET_EMPLOYEEID_SUCCESS = "GET_EMPLOYEEID_SUCCESS";
export const GET_EMPLOYEEID_FAILED = "GET_EMPLOYEEID_FAILED";

export const ADD_EMPLOYEE_LOAD = "ADD_EMPLOYEE_LOAD";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_FAILED = "ADD_EMPLOYEE_FAILED";

export const EDIT_EMPLOYEE_LOAD = "EDIT_EMPLOYEE_LOAD";
export const EDIT_EMPLOYEE_SUCCESS = "EDIT_EMPLOYEE_SUCCESS";
export const EDIT_EMPLOYEE_FAILED = "EDIT_EMPLOYEE_FAILED";

export const DELETE_EMPLOYEE_LOAD = "DELETE_EMPLOYEE_LOAD";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_FAILED = "DELETE_EMPLOYEE_FAILED";

/** PRODUCT TYPE */
export const GET_PRODUCT_LOAD = "GET_PRODUCT_LOAD";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILED = "GET_PRODUCT_FAILED";

export const GET_PRODUCTID_LOAD = "GET_PRODUCTID_LOAD";
export const GET_PRODUCTID_SUCCESS = "GET_PRODUCTID_SUCCESS";
export const GET_PRODUCTID_FAILED = "GET_PRODUCTID_FAILED";

export const ADD_PRODUCT_LOAD = "ADD_PRODUCT_LOAD";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";

export const EDIT_PRODUCT_LOAD = "EDIT_PRODUCT_LOAD";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAILED = "EDIT_PRODUCT_FAILED";

export const DELETE_PRODUCT_LOAD = "DELETE_PRODUCT_LOAD";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

export const GET_TROLI_LOAD = "GET__TROLI_LOAD";
export const GET_TROLI_SUCCESS = "GET__TROLI_SUCCESS";
export const GET_TROLI_FAILED = "GET__TROLI_FAILED";

export const ADD_TROLI_LOAD = "ADD__TROLI_LOAD";
export const ADD_TROLI_SUCCESS = "ADD__TROLI_SUCCESS";
export const ADD_TROLI_FAILED = "ADD__TROLI_FAILED";

export const UPDATE_TROLI_SUCCES = "UPDATE_TROLI_SUCCES";

export const DELETE_TROLI_LOAD = "DELETE__TROLI_LOAD";
export const DELETE_TROLI_SUCCESS = "DELETE__TROLI_SUCCESS";
export const DELETE_TROLI_FAILED = "DELETE__TROLI_FAILED";
/** PRODUCT TYPE SHARING*/
export const AVALIABLE_PRODUCT_LOAD = "AVALIABLE_PRODUCT_LOAD";
export const AVALIABLE_PRODUCT_SUCCESS = "AVALIABLE_PRODUCT_SUCCESS";
export const AVALIABLE_PRODUCT_FAILED = "AVALIABLE_PRODUCT_FAILED";

export const FORADMIN_PRODUCT_LOAD = "FORADMIN_PRODUCT_LOAD";
export const FORADMIN_PRODUCT_SUCCESS = "FORADMIN_PRODUCT_SUCCESS";
export const FORADMIN_PRODUCT_FAILED = "FORADMIN_PRODUCT_FAILED";

export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const SET_SUBMITTED_TERM = "SET_SUBMITTED_TERM";
/** PRODUCT CATEGORY */
export const GET_PRODUCT_WITH_CATEGORY_LOAD = "GET_PRODUCT_WITH_CATEGORY_LOAD";
export const GET_PRODUCT_WITH_CATEGORY_SUCCESS =
  "GET_PRODUCT_WITH_CATEGORY_SUCCESS";
export const GET_PRODUCT_WITH_CATEGORY_FAILED =
  "GET_PRODUCT_WITH_CATEGORY_FAILED";

export const GET_CATEGORY_LOAD = "GET_CATEGORY_LOAD";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILED = "GET_CATEGORY_FAILED";

export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";

export const GET_CATEGORYID_LOAD = "GET_CATEGORYID_LOAD";
export const GET_CATEGORYID_SUCCESS = "GET_CATEGORYID_SUCCESS";
export const GET_CATEGORYID_FAILED = "GET_CATEGORYID_FAILED";

export const ADD_CATEGORY_LOAD = "ADD_CATEGORY_LOAD";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILED = "ADD_CATEGORY_FAILED";

export const EDIT_CATEGORY_LOAD = "EDIT_CATEGORY_LOAD";
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";
export const EDIT_CATEGORY_FAILED = "EDIT_CATEGORY_FAILED";

export const DELETE_CATEGORY_LOAD = "DELETE_CATEGORY_LOAD";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILED = "DELETE_CATEGORY_FAILED";

/** TRANSACTION */
export const LIST_TRX_LOAD = "LIST_TRX_LOAD";
export const LIST_TRX_SUCCESS = "LIST_TRX_SUCCESS";
export const LIST_TRX_FAILED = "LIST_TRX_FAILED";

export const ADD_TRX_LOAD = "ADD_TRX_LOAD";
export const ADD_TRX_SUCCESS = "ADD_TRX_SUCCESS";
export const ADD_TRX_FAILED = "ADD_TRX_FAILED";

export const DETAIL_TRX_LOAD = "DETAIL_TRX_LOAD";
export const DETAIL_TRX_SUCCESS = "DETAIL_TRX_SUCCESS";
export const DETAIL_TRX_FAILED = "DETAIL_TRX_FAILED";

export const GET_INVOICEALL_LOAD = "GET_INVOICEALL_LOAD";
export const GET_INVOICEALL_SUCCESS = "GET_INVOICEALL_SUCCESS";
export const GET_INVOICEALL_FAILED = "GET_INVOICEALL_FAILED";

export const GET_INVOICE_ID_LOAD = "GET_INVOICE_ID_LOAD";
export const GET_INVOICE_ID_SUCCESS = "GET_INVOICE_ID_SUCCESS";
export const GET_INVOICE_ID_FAILED = "GET_INVOICE_ID_FAILED";